# Newton Forward Interpolation

In [4]:
import numpy as np


def newton_forward_interpolation(x, y, value):
    """
    Perform Newton Forward Interpolation to estimate the value of a function at a given point.

    Parameters:
    - x: Array of data points for the independent variable.
    - y: Array of corresponding values of the dependent variable.
    - value: The x-coordinate at which the function value is to be estimated.

    Returns:
    - interpolated_value: The estimated value of the function at `value`.
    """
    n = len(x)

    # Create the difference table
    diff_table = np.zeros((n, n))
    diff_table[:, 0] = y  # First column is the y-values

    for j in range(1, n):
        for i in range(n - j):
            diff_table[i, j] = diff_table[i + 1, j - 1] - diff_table[i, j - 1]

    # Calculate u
    h = x[1] - x[0]  # Assuming uniform spacing
    u = (value - x[0]) / h

    # Calculate the interpolated value
    interpolated_value = diff_table[0, 0]
    u_term = 1  # Product term for u

    for i in range(1, n):
        u_term *= (u - (i - 1)) / i  # Update the u_term for each term
        interpolated_value += u_term * diff_table[0, i]

    return interpolated_value, diff_table


# Example usage
x_points = np.array([0, 1, 2, 3, 4])  # Known x values
y_points = np.array([1, 2, 4, 8, 16])  # Corresponding y values (e.g., 2^x)

# Interpolate the value of the function at x = 2.5
value_to_interpolate = 2.5
interpolated_value, difference_table = newton_forward_interpolation(
    x_points, y_points, value_to_interpolate)

print(f"Interpolated value at x = {value_to_interpolate}: {interpolated_value}")
print("\nDifference Table:")
print(difference_table)

Interpolated value at x = 2.5: 5.6484375

Difference Table:
[[ 1.  1.  1.  1.  1.]
 [ 2.  2.  2.  2.  0.]
 [ 4.  4.  4.  0.  0.]
 [ 8.  8.  0.  0.  0.]
 [16.  0.  0.  0.  0.]]


# Newton Backward Interpolation

In [5]:
import numpy as np


def newton_backward_interpolation(x, y, value):
    """
    Perform Newton Backward Interpolation to estimate the value of a function at a given point.

    Parameters:
    - x: Array of data points for the independent variable.
    - y: Array of corresponding values of the dependent variable.
    - value: The x-coordinate at which the function value is to be estimated.

    Returns:
    - interpolated_value: The estimated value of the function at `value`.
    """
    n = len(x)

    # Create the backward difference table
    diff_table = np.zeros((n, n))
    diff_table[:, 0] = y  # First column is the y-values

    for j in range(1, n):
        for i in range(n - 1, j - 1, -1):
            diff_table[i, j] = diff_table[i, j - 1] - diff_table[i - 1, j - 1]

    # Calculate u
    h = x[1] - x[0]  # Assuming uniform spacing
    u = (value - x[-1]) / h

    # Calculate the interpolated value
    interpolated_value = diff_table[-1, 0]
    u_term = 1  # Product term for u

    for i in range(1, n):
        u_term *= (u + (i - 1)) / i  # Update the u_term for each term
        interpolated_value += u_term * diff_table[-1, i]

    return interpolated_value, diff_table


# Example usage
x_points = np.array([0, 1, 2, 3, 4])  # Known x values
y_points = np.array([1, 2, 4, 8, 16])  # Corresponding y values (e.g., 2^x)

# Interpolate the value of the function at x = 3.5
value_to_interpolate = 3.5
interpolated_value, difference_table = newton_backward_interpolation(
    x_points, y_points, value_to_interpolate)

print(f"Interpolated value at x = {value_to_interpolate}: {interpolated_value}")
print("\nBackward Difference Table:")
print(difference_table)

Interpolated value at x = 3.5: 11.3359375

Backward Difference Table:
[[ 1.  0.  0.  0.  0.]
 [ 2.  1.  0.  0.  0.]
 [ 4.  2.  1.  0.  0.]
 [ 8.  4.  2.  1.  0.]
 [16.  8.  4.  2.  1.]]


# Newton Dynamic Interpolation

In [8]:
import numpy as np


def newton_forward_interpolation(x, y, value):
    """
    Perform Newton Forward Interpolation to estimate the value of a function at a given point.

    Parameters:
    - x: Array of data points for the independent variable.
    - y: Array of corresponding values of the dependent variable.
    - value: The x-coordinate at which the function value is to be estimated.

    Returns:
    - interpolated_value: The estimated value of the function at `value`.
    """
    n = len(x)

    # Create the forward difference table
    diff_table = np.zeros((n, n))
    diff_table[:, 0] = y  # First column is the y-values

    for j in range(1, n):
        for i in range(n - j):
            diff_table[i, j] = diff_table[i + 1, j - 1] - diff_table[i, j - 1]

    # Calculate u
    h = x[1] - x[0]  # Assuming uniform spacing
    u = (value - x[0]) / h

    # Calculate the interpolated value
    interpolated_value = diff_table[0, 0]
    u_term = 1  # Product term for u

    for i in range(1, n):
        u_term *= (u - (i - 1)) / i  # Update the u_term for each term
        interpolated_value += u_term * diff_table[0, i]

    return interpolated_value, diff_table


def newton_backward_interpolation(x, y, value):
    """
    Perform Newton Backward Interpolation to estimate the value of a function at a given point.

    Parameters:
    - x: Array of data points for the independent variable.
    - y: Array of corresponding values of the dependent variable.
    - value: The x-coordinate at which the function value is to be estimated.

    Returns:
    - interpolated_value: The estimated value of the function at `value`.
    """
    n = len(x)

    # Create the backward difference table
    diff_table = np.zeros((n, n))
    diff_table[:, 0] = y  # First column is the y-values

    for j in range(1, n):
        for i in range(n - 1, j - 1, -1):
            diff_table[i, j] = diff_table[i, j - 1] - diff_table[i - 1, j - 1]

    # Calculate u
    h = x[1] - x[0]  # Assuming uniform spacing
    u = (value - x[-1]) / h

    # Calculate the interpolated value
    interpolated_value = diff_table[-1, 0]
    u_term = 1  # Product term for u

    for i in range(1, n):
        u_term *= (u + (i - 1)) / i  # Update the u_term for each term
        interpolated_value += u_term * diff_table[-1, i]

    return interpolated_value, diff_table


def dynamic_newton_interpolation(x, y, value):
    """
    Apply Newton Forward or Backward Interpolation depending on the proximity of `value` to the 
    first or last x-value in the dataset.

    Parameters:
    - x: Array of data points for the independent variable.
    - y: Array of corresponding values of the dependent variable.
    - value: The x-coordinate at which the function value is to be estimated.

    Returns:
    - interpolated_value: The estimated value of the function at `value`.
    """
    if value < x[len(x)//2]:  # If value is closer to the first half of the data (using forward)
        print("Using Newton Forward Interpolation\n")
        return newton_forward_interpolation(x, y, value)
    else:  # If value is closer to the second half of the data (using backward)
        print("Using Newton Backward Interpolation\n")
        return newton_backward_interpolation(x, y, value)


# Example usage
x_points = np.array([0, 1, 2, 3, 4])  # Known x values
y_points = np.array([1, 2, 4, 8, 16])  # Corresponding y values (e.g., 2^x)

# Interpolate the value of the function at x = 3.5
value_to_interpolate = 3.5
interpolated_value, difference_table = dynamic_newton_interpolation(
    x_points, y_points, value_to_interpolate)

print(f"Interpolated value at x = {value_to_interpolate}: {interpolated_value}")
print("\nDifference Table:")
print(difference_table)

Using Newton Backward Interpolation

Interpolated value at x = 3.5: 11.3359375

Difference Table:
[[ 1.  0.  0.  0.  0.]
 [ 2.  1.  0.  0.  0.]
 [ 4.  2.  1.  0.  0.]
 [ 8.  4.  2.  1.  0.]
 [16.  8.  4.  2.  1.]]
